@startuml
autonumber

actor Client as C
boundary Interface as I
control PortfolioManager as PM
entity Engine as E
control DataManager as DM
database Database as DB


C -> I ++: run
    alt command == "experiment"
        I -> PM ++: experiment
            group Load data
                PM -> DM ++: Request data
                    DM -> DB ++: Request data
                        return Raw data
                    deactivate
            end

            loop until the last test date
                group Train
                    PM -> E ++: **Train**: Request optimal portfolio
                        E -> E ++: Process data
                            E -> DM ++: Process data
                                return Processed data
                        deactivate E

                        ==Complete (21/11/08)==

                        group Compute optimal portfolio
                            E -> E ++: Compute optimal portfolio
                            deactivate
                        end
                        return Optimal portfolio, train result
                end

                group Test
                    PM -> E ++: **Test**: Invest with optimal portfolio
                        loop until stop condition is True
                            group Invest day by day
                                E -> E ++: Process data
                                    E -> DM ++: Process data
                                        return Processed data
                                deactivate E

                                E -> E ++: Invest day by day
                                deactivate
                            end
                        end
                        return Test result
                end

                group Postprocessing
                    PM -> PM ++: Postprocessing
                        PM -> DB: Save results
                    deactivate
                end
            end
        deactivate
    else
        |||
    end
@enduml
